# Source:

Combined Notes from Udemy Videos  

- 2024 Master class on Data Science using Python A-Z for ML
- Data Science and Machine Learning Basic to Advanced


  
  

In [ ]:
import numpy as np

# **Module**
module is a file containing Python definitons and statements

Ways to import module
*   import evrything from the module for immediate use
*   import a specific function/ variable from the module
*   import everything from the module with alias name

**import evrything from the module for immediate use**

Ex: from math import *

**import a specific function/ variable from the module**

Ex: from math import pi

**import everything from the module with alias name**

Ex: import numpy as np






List is a mutable dsts structure in Python which can contains multiple values.


List
-------
list can contain different data types.

when it comes to massive amount, it's very slow.

computational cost

it costs a lot of memory


NumPy - Numeric Python
-------
we can create n-dimensonal Array

we can do math functions with the array


In [ ]:
l = [1,2,3,4,5]
print(l)

[1, 2, 3, 4, 5]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
arr
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# 1D Array
a0 = np.array([40])
print(a0)
a1 = np.array([50,60,70])
print(a1)

[40]
[50 60 70]


In [ ]:
# 2D Array
a2 = np.array([[1,2,3] , [4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D Array
a3 = np.array([[[1,2,3,20],[4,5,6,21]],[[7,8,9,22],[10,11,12,23]],[[13,14,15,16],[17,18,19,24]]])
print(a3)

[[[ 1  2  3 20]
  [ 4  5  6 21]]

 [[ 7  8  9 22]
  [10 11 12 23]]

 [[13 14 15 16]
  [17 18 19 24]]]


In [ ]:
#Check Dimensions [ndim]

print(a0.ndim)
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
1
2
3


In [ ]:
# Shape - find the dimension of the array
print(a0.shape)
print(a1.shape)
print(a2.shape)
print(a3.shape)

(1,)
(3,)
(2, 3)
(3, 2, 4)


In [ ]:
# Reshaping - we can add or remove the dimension or change the no of elements in the dimension

#Reshape
# 1D - 2D
# 1D - 3D

# 2D - 2D
# 2D - 3D

# 3D - 2D
# 3D - 3D


# 1D - 2D
print('1D - 2D')
print('-------------------------')
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a1 = a.reshape(6,2)
print(a.shape)
print(a1.shape)
a1 = a.reshape(2,6)
print(a1.shape)
print()

# 1D - 3D
print('1D - 3D')
print('-------------------------')
a1 = a.reshape(3,2,2)
print(a.shape)
print(a1.shape)
print()

# 2D - 2D
print('2D - 2D')
print('-------------------------')
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a.shape)
a1 = a.reshape(2,6)
print(a1.shape)
print()


# 2D - 3D
print('2D - 3D')
print('-------------------------')
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a.shape)
a1 = a.reshape(3,2,2)
print(a1.shape)
print()



# 3D - 2D
print('3D - 2D')
a = np.array([[[1,2],[3,4],[5,6],[7,8]],[[9,10],[11,12],[13,14],[15,16]],[[17,18],[19,20],[21,22],[23,24]]])
print(a)
print(a.shape)
a1 = a.reshape(6,4)
print(a1)
print(a1.shape)
print()


# 3D - 3D
print('3D - 3D')
a = np.array([[[1,2],[3,4],[5,6],[7,8]],[[9,10],[11,12],[13,14],[15,16]],[[17,18],[19,20],[21,22],[23,24]]])
print(a)
print(a.shape)
print()
a1 = a.reshape(4,3,2)
print(a1)
print(a1.shape)
print()

# 3D - 1D
print('3D - 1D')
a = np.array([[[1,2],[3,4],[5,6],[7,8]],[[9,10],[11,12],[13,14],[15,16]],[[17,18],[19,20],[21,22],[23,24]]])
print(a)
print(a.shape)
print()
a1 = a.reshape(24,)
print(a1)
print(a1.shape)
print()



1D - 2D
-------------------------
(12,)
(6, 2)
(2, 6)

1D - 3D
-------------------------
(12,)
(3, 2, 2)

2D - 2D
-------------------------
(3, 4)
(2, 6)

2D - 3D
-------------------------
(3, 4)
(3, 2, 2)

3D - 2D
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
(3, 4, 2)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
(6, 4)

3D - 3D
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
(3, 4, 2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
(4, 3, 2)

3D - 1D
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
(3, 4, 2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(24,)



In [ ]:
# Reshape(-1) - convert multi dimentional array into 1D array

# 2D - 1D

# 3D - 1D


# 2D - 1D
print('2D - 1D')
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape)
a1 = a.reshape(-1)
print(a1)
print(a1.shape)
print()


# 3D - 1D
print('3D - 1D')
a = np.array([[[1,2],[3,4],[5,6],[7,8]],[[9,10],[11,12],[13,14],[15,16]],[[17,18],[19,20],[21,22],[23,24]]])
print(a)
print(a.shape)
a1 = a.reshape(-1)
print(a1)
print(a1.shape)
print()


'''
a = [1,2,3,4,5,6]
The size of a = 6
It can be reshaped into (1,6), (6,1), (2,3), (3,2)
when we use -1 in reshape: The value -1 is be ready to assigned o a value which can maintain the size of the array a.

Ex 1:
a1 = a.reshape(-1)
shape of a1 = (6,)
size of a1 = 6

a2 = a.reshape(6)
shape of a2 = (6,)
size of a2 = 6

That means; a.reshape(-1) = a.reshape(6)
we need to maintain the size as 6, so in a2 the value '-1' is assigned to 6 automatically.

Ex 2:
a4 = a.reshape(-1,2)
here the '-1' will be assigned to '3' automatically.
because [ Y*2 = 6 ] => Y=3 => '-1' is changed as '3'

Ex 3:
a5 =a.reshape(3,-1)
here '-1' will be changed to '2' automatically.
because [ 3*Y = 6 ] => Y = 2 => '-1' is changed as '2'
'''



2D - 1D
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[1 2 3 4 5 6 7 8]
(8,)

3D - 1D
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
(3, 4, 2)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(24,)



In [ ]:
# Flattening - transform 2D, 3D array into 1D array
            # there is a diffrence between 'flatten' and 'reshape(-1)'


a = np.array([[[1,2],[3,4],[5,6],[7,8]],[[9,10],[11,12],[13,14],[15,16]],[[17,18],[19,20],[21,22],[23,24]]])
print(a.shape)
print()

a1 = a.flatten()
print(a1.shape)

(3, 4, 2)

(24,)


In [ ]:
# Indexing

# 1D Array
print('Access 1D Array')
a = np.array([1,2,3,4,5])
print(a[0])
print(a[1] + a[3])


# 2D Array
print('Access 2D Array')
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a[0,3])
print(a[1,2])
print()

# 3D Array
print('Accessing 3D Array')
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a[0,1,1])


Access 1D Array
1
6
Access 2D Array
4
7

Accessign 3D Array
5


In [ ]:
# Negative Indexing in 2D Array

a= np.array([[1,2,3],[4,5,6],[7,8,9]])
# a[1,-1] = a[1,-2] = a[-2,-2]
print(a[1,1])
print(a[1,-2])

print(a[-2,-2])

5
5
5


In [ ]:
# Iterating

# 1D Array
print('Iteration in 1D Array')
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

for x in a:
  print(x)
print()

for x in a:
  print(x, end=' ')
print()
print()


# 2D Array
print('Iteration in 2D Array')
a = np.array([[1,2,3,4],[5,6,7,8]])

for x in a:
  print(x)
print()

for x in a:
  for y in x:
    print(y, end=' ')
  print()
print()


for i in range(len(a)):
  for j in range(len(a[i])):
    print(a[i,j], end=' ')
  print()

print()
print()


# 3D Array
print('Iteration in 3D Array')
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in a:
  for y in x:
    for z in y:
      print(z , end=' ')
    print()
  print()


for i in range(len(a)):
  for j in range(len(a[i])):
    for k in range(len(a[i,j])):
      print(a[i,j,k], end=' ')
    print()
  print()


print()


Iteration in 1D Array
1
2
3
4
5
6
7
8
9
10
11
12

1 2 3 4 5 6 7 8 9 10 11 12 

Iteration in 2D Array
2
[1 2 3 4]
[5 6 7 8]

1 2 3 4 
5 6 7 8 

1 2 3 4 
5 6 7 8 


Iteration in 3D Array
1 2 3 
4 5 6 

7 8 9 
10 11 12 

1 2 3 
4 5 6 

7 8 9 
10 11 12 




In [ ]:
# Slicing

    # [start:end]
    # [start:end:step]
    # [start:] => ends with the last element
    # [:end] => starts from 0
    # [start:end] => steps with 0

# Negative Slicing
print('Negative Slicing')
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[-1])
print(a[-5:-2])
print()

# 1D Array
print('Slicing in 1D Array')
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[0:3])
print(a[:3])
print(a[0:5])
print(a[0:])
print(a[1:8:1])
print(a[1:8:2])
print()

# 2D Array
print('Slicing in 2D Array')
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[1, 2:4])
print(a[0,0:])

# 3D Array
print('Slicing in 3D Array')
a = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]])
print(a[1,0,2:])


Negative Slicing
10
[6 7 8]

Slicing in 1D Array
[1 2 3]
[1 2 3]
[1 2 3 4 5]
[ 1  2  3  4  5  6  7  8  9 10]
[2 3 4 5 6 7 8]
[2 4 6 8]

Slicing in 2D Array
[8 9]
[1 2 3 4 5]
Slicing in 3D Array
[11 12]


In [ ]:
# Search

a = np.array([1,2,3,5,7,6,4,3,8,9,10,3])
print(np.where(a == 3))
print(np.where(a%2 == 0))


(array([ 2,  7, 11]),)
(array([ 1,  5,  6,  8, 10]),)


(array([ 2,  7, 11]),)

In [ ]:
# Sorting
a = np.array([5,7,2,8,1])
print(np.sort(a))

b = np.array(['banana','cherry','apple'])
print(np.sort(b))

[1 2 5 7 8]
['apple' 'banana' 'cherry']


In [ ]:
# Arange - we can create an instance array using 'arange' function
          # arange(start, end, step)


a = np.arange(10)
print(a)
a0 = np.arange(0,10)
print(a0)
a1 = np.arange(0,10,2)
print(a1)
a1 = np.arange(10,2)
print(a1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[]


In [ ]:
# Linespace - Same like Arange
            # We can create an array instanly using 'linspace' function.
            # linspace(start, end, how many numbers we need )
            # based on how many numbers we need, it will create the interval between start and end numbers

a = np.linspace(1,15,30)
print(a)
print()

a = np.linspace(1,15,15)
print(a)
print()

a = np.linspace(1,15,10)
print(a)
print()


[ 1.          1.48275862  1.96551724  2.44827586  2.93103448  3.4137931
  3.89655172  4.37931034  4.86206897  5.34482759  5.82758621  6.31034483
  6.79310345  7.27586207  7.75862069  8.24137931  8.72413793  9.20689655
  9.68965517 10.17241379 10.65517241 11.13793103 11.62068966 12.10344828
 12.5862069  13.06896552 13.55172414 14.03448276 14.51724138 15.        ]

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]

[ 1.          2.55555556  4.11111111  5.66666667  7.22222222  8.77777778
 10.33333333 11.88888889 13.44444444 15.        ]



In [ ]:
# Random - to create an array with random floating numbers in the range of 0 and 1.
      # [0,1)]
a = np.random.rand(10)
print(a)
print()

a = np.random.rand(20)
print(a)

[0.13885561 0.21761063 0.7516148  0.61158892 0.61237454 0.92179764
 0.61765147 0.61521931 0.59771843 0.86854676]

[0.14304633 0.83620502 0.04980856 0.09759145 0.94301095 0.54818243
 0.45545858 0.81907965 0.55284319 0.66279292 0.54117075 0.29064847
 0.13256657 0.86737251 0.18701995 0.6913217  0.24159626 0.8673263
 0.13487093 0.29437112]


In [ ]:
# Random Matrix - Creating an multi-dimensional array with random floating numbers in the range of 0 and 1.

a = np.random.rand(3,4)
print(a)
print()

a = np.random.rand(5,5,2)
print(a)


[[0.55120206 0.22969994 0.84909562 0.46268343]
 [0.83436911 0.02929604 0.62346395 0.0450939 ]
 [0.19366423 0.22209889 0.11069258 0.73317128]]

[[[0.92542076 0.93553606]
  [0.79183388 0.35894438]
  [0.27007537 0.23001284]
  [0.58959233 0.50174458]
  [0.53589663 0.02101097]]

 [[0.43531549 0.24361157]
  [0.04675659 0.22950858]
  [0.64640175 0.52860298]
  [0.94735442 0.18713451]
  [0.39291773 0.47106485]]

 [[0.94294106 0.09624085]
  [0.20409382 0.77697501]
  [0.50304413 0.03651949]
  [0.80540558 0.66675211]
  [0.13890522 0.36534631]]

 [[0.31492992 0.93361057]
  [0.2636223  0.45089277]
  [0.80541718 0.87964626]
  [0.82084156 0.2276656 ]
  [0.09549145 0.67543242]]

 [[0.58565409 0.62346812]
  [0.67093574 0.97313636]
  [0.73365192 0.95565278]
  [0.6018439  0.36305189]
  [0.4892816  0.1987484 ]]]


In [ ]:
# Diagonal Matrix - It will create a diagonal matrix for the given numbers.

a = np.diag([1,3,5])
print(a)
print()

a = np.diag([1,2,3,4,5])
print(a)

[[1 0 0]
 [0 3 0]
 [0 0 5]]

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
# Trace - find the sum of diagonal elements

a = np.array([[1,2,3],[10,11,12],[9,7,8]])
print(a)
print()

print(a.trace())  # (1 + 11 + 8) = 20
print()

# Another way of finding the trace value  - sum(a.diagonal())
print('Sum of Diagonal is : ',sum(a.diagonal()))

[[ 1  2  3]
 [10 11 12]
 [ 9  7  8]]

20

Sum of Diagonal is :  20


In [ ]:
# Transpose - to invert the shape of an array
# np.transpose(a) OR a.T OR a.transpose()
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
print()
print(a.transpose())
print()

print(a.shape)
print(a.transpose().shape)
print('-----------')
a2 = a.transpose()
print(a2.shape)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]

(4, 3)
(3, 4)
-----------
(3, 4)


In [ ]:
# Zeros
a = np.zeros(6)
print(a)

# Multidimensional Zeros
a = np.zeros((4,5))
print(a)

# Full
a = np.full((10), 7)
print(a)

# Multidimensional Full
a = np.full((4,6),8)
print(a)

# Convert Pyton List into Numy Array
li = [1,2,3,4,5]
a = np.array(li)
print(a)


[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[7 7 7 7 7 7 7 7 7 7]
[[8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]]
[1 2 3 4 5]


In [ ]:
# Filtering

a1 = np.array([1,2,4,5,8,4,9,4])
print(a1)
a2 = a1[a1>4]
print(a2)
a2 = a2[a2%2 == 1]
print(a2)
print()

arr = np.array([41,42,43,44])
x = [True,False,True,False]
print(arr)
print(x)
print()
n_arr = arr[x]
print(n_arr)


[1 2 4 5 8 4 9 4]
[5 8 9]
[5 9]

[41 42 43 44]
[True, False, True, False]

[41 43]


In [ ]:
# Check given array is empty or not

a = np.array([1,2,3,4,5])
print('Size: ',a.size)
print('Length: ', len(a))
print('-----------')
a = np.array([[1,2,3,4],[5,6,7,8]])
print('Size: ',a.size)
print('Length: ', len(a))


if (a.size == 0) :
  print('A is Empty')
else:
  print('A is Not Empty')

print(len(a))
print()


b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b.size)
if (b.size == 0):
  print('B is Empty')
else:
  print('B is Not Empty')
print()

Size:  5
Length:  5
-----------
Size:  8
Length:  2
A is Not Empty
2

10
B is Not Empty



In [ ]:
# Identity Matrix - it must be a square matrix

a = np.eye(3)
print(a)
print()

a1 = np.eye(5)
print(a1)
print()

a2 = np.eye(5,3)
print(a2)
print()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]

