Numeric Python

List
-------
list can contain different data types.
when it comes to massive amount, it's very slow.
computational cost
it costs a lot of memory

NumPy
-------
we can create n-dimensonal Array
we can do math functions with the array


In [ ]:
l = [1,2,3,4,5]
print(l)

[1, 2, 3, 4, 5]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
arr
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# 1D Array
a0 = np.array([40])
print(a0)
a1 = np.array([50,60,70])
print(a1)

[40]
[50 60 70]


In [ ]:
# 2D Array
a2 = np.array([[1,2,3] , [4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D Array
a3 = np.array([[[1,2,3,20],[4,5,6,21]],[[7,8,9,22],[10,11,12,23]],[[13,14,15,16],[17,18,19,24]]])
print(a3)

[[[ 1  2  3 20]
  [ 4  5  6 21]]

 [[ 7  8  9 22]
  [10 11 12 23]]

 [[13 14 15 16]
  [17 18 19 24]]]


In [ ]:
#Check Dimensions [ndim]

print(a0.ndim)
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
1
2
3


In [ ]:
# Shape
print(a0.shape)
print(a1.shape)
print(a2.shape)
print(a3.shape)

(1,)
(3,)
(2, 3)
(3, 2, 4)


In [ ]:
# Reshaping - we can add or remove the dimension or change the no of elements in the dimension

#Reshape
# 1D - 2D
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a1 = a.reshape(6,2)
print(a1)
print()
a1 = a.reshape(2,6)
print(a1)
print()

# 1D - 3D
a1 = a.reshape(3,2,2)
print(a1)
print()


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
# Flattening - convert multi dimentional array into 1D array

# 2D - 1D
# 2D - 2D

# 3D - 1D
# 3D - 2D
# 3D - 3D

In [ ]:
# 2D - 1D
print('2D - 1D')
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape)
a1 = a.reshape(-1)
print(a1)
print(a1.shape)
print()

2D - 1D
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[1 2 3 4 5 6 7 8]
(8,)



In [ ]:
# 2D - 2D
print('2D - 2D')
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape)
print()

a1 = a.reshape(4,2)
print(a1)
print(a1.shape)
print()

2D - 2D
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)



In [ ]:
# 3D - 1D
print('3D - 1D')
a = np.array([[[1,2],[3,4],[5,6],[7,8]],[[9,10],[11,12],[13,14],[15,16]],[[17,18],[19,20],[21,22],[23,24]]])
print(a)
print(a.shape)
a1 = a.reshape(-1)
print(a1)
print(a1.shape)
print()

3D - 1D
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
(3, 4, 2)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(24,)



In [ ]:
#3D - 2D
print('3D - 2D')
a = np.array([[[1,2],[3,4],[5,6],[7,8]],[[9,10],[11,12],[13,14],[15,16]],[[17,18],[19,20],[21,22],[23,24]]])
print(a)
print(a.shape)
a1 = a.reshape(6,4)
print(a1)
print(a1.shape)
print()

3D - 2D
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
(3, 4, 2)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
(6, 4)



In [ ]:
# 3D - 3D
print('3D - 3D')
a = np.array([[[1,2],[3,4],[5,6],[7,8]],[[9,10],[11,12],[13,14],[15,16]],[[17,18],[19,20],[21,22],[23,24]]])
print(a)
print(a.shape)
print()
a1 = a.reshape(4,3,2)
print(a1)
print(a1.shape)
print()


3D - 3D
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
(3, 4, 2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
(4, 3, 2)



In [ ]:
# Indexing

# 1D Array
print('Access 1D Array')
a = np.array([1,2,3,4,5])
print(a[0])
print(a[1] + a[3])


# 2D Array
print('Access 2D Array')
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a[0,3])
print(a[1,2])
print()

# 3D Array
print('Accessing 3D Array')
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a[0,1,1])


Access 1D Array
1
6
Access 2D Array
4
7

Accessign 3D Array
5


In [ ]:
# Iterating

# 1D Array
print('Iteration in 1D Array')
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

for x in a:
  print(x)
print()

# 2D Array
print('Iteration in 1D Array')
a = np.array([[1,2,3,4],[5,6,7,8]])

for x in a:
  print(x)
print()

for x in a:
  for y in x:
    print(y)
print()


# 3D Array
print('Iteration in 3D Array')
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in a:
  print(x)
print()

for x in a:
  for y in x:
    print(y)
print()

for x in a:
  for y in x:
    for z in y:
      print(z)
print()


Iteration in 1D Array
1
2
3
4
5
6
7
8
9
10
11
12

Iteration in 1D Array
[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8

Iteration in 3D Array
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]

1
2
3
4
5
6
7
8
9
10
11
12



In [ ]:
# Slicing

    # [start:end]
    # [start:end:step]
    # [start:] => ends with the last element
    # [:end] => starts from 0
    # [start:end] => steps with 0

# Negative Slicing
print('Negative Slicing')
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[-1])
print(a[-5:-2])
print()

# 1D Array
print('Slicing in 1D Array')
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[0:3])
print(a[:3])
print(a[0:5])
print(a[0:])
print(a[1:8:1])
print(a[1:8:2])
print()

# 2D Array
print('Slicing in 2D Array')
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[1, 2:4])
print(a[0,0:])

# 3D Array
print('Slicing in 3D Array')
a = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]])
print(a[1,0,2:])


Negative Slicing
10
[6 7 8]

Slicing in 1D Array
[1 2 3]
[1 2 3]
[1 2 3 4 5]
[ 1  2  3  4  5  6  7  8  9 10]
[2 3 4 5 6 7 8]
[2 4 6 8]

Slicing in 2D Array
[8 9]
[1 2 3 4 5]
Slicing in 3D Array
[11 12]


In [ ]:
# Search

a = np.array([1,2,3,5,7,6,4,3,8,9,10,3])
print(np.where(a == 3))
print(np.where(a%2 == 0))


(array([ 2,  7, 11]),)
(array([ 1,  5,  6,  8, 10]),)


(array([ 2,  7, 11]),)

In [ ]:
# Sorting
a = np.array([5,7,2,8,1])
print(np.sort(a))

b = np.array(['banana','cherry','apple'])
print(np.sort(b))

[1 2 5 7 8]
['apple' 'banana' 'cherry']


In [ ]:
# Arange
a = np.arange(10)
print(a)
a1 = np.arange(0,10,2)
print(a1)
a1 = np.arange(10,2)
print(a1)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[]


In [ ]:
# Zeros
a = np.zeros(6)
print(a)

# Multidimensional Zeros
a = np.zeros((4,5))
print(a)

# Full
a = np.full((10), 7)
print(a)

# Multidimensional Full
a = np.full((4,6),8)
print(a)

# Convert Pyton List into Numy Array
li = [1,2,3,4,5]
a = np.array(li)
print(a)


[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[7 7 7 7 7 7 7 7 7 7]
[[8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]]
[1 2 3 4 5]


In [ ]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])